### ISSUE TITLE
`kubectl get nodes` returning an error

### ISSUE THREAD

**Issue by dwaynebradley** [iwilltry42/k3d-demo#1]
Walking through the `make demo` scenario, when I get to the step `kubectl get nodes` I'm getting the following error:

```
Error from server (InternalError): an error on the server ("") has prevented the request from succeeding
```

OS: Fedora 32
Docker: `Docker version 19.03.8, build afacb8b7f0`
k3d: `k3d version v3.0.0-beta.1`
kubectl: `Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`

I can't figure out what I'm missing...

**Comment by iwilltry42** [comment]
Hi @dwaynebradley, thanks for opening this issue!
Can you please paste the output of the whole script up to this point?
And the output of `docker ps -a` at the time this is happening?

**Comment by iwilltry42** [comment]
Any update on this @dwaynebradley ?

**Comment by dwaynebradley** [comment]
Hey @iwilltry42 ! Unfortunately, after upgrading to Windows 10 2004, I cannot even get my Fedora VM to boot any longer. No idea what happened. Good thing there wasn't anything critical in there. I guess you can just go ahead and close this for now as I don't have a means of recreating the error.

**Comment by iwilltry42** [comment]
Hi @dwaynebradley. Damn, that's bad luck 😕
You may as well use k3d with windows or WSL though, if you want to use it 👍
Just the demo scripts probably port to push that easily..

**Comment by sjbeskur** [comment]
I too am experiencing the same issues.   k3d cluster seems to be working fine but after a period of time the cluster will completely hang when attempting to run kubectl commands.   Only solution I've found is to blow away the whole thing and start over.

Here is output from:
`docker ps -a`


```
super@sjb-svr1:~$ kubectl get nodes
Error from server (InternalError): an error on the server ("") has prevented the request from succeeding

super@sjb-svr1:~$ docker ps -a
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS                      PORTS                             NAMES
84f07b6ed0f9        rancher/k3d-proxy:v3.0.1   "/bin/sh -c nginx-pr…"   22 hours ago        Up 22 hours                 80/tcp, 0.0.0.0:43891->6443/tcp   k3d-nemesis-cluster-serverlb
1b5da4368e2f        rancher/k3s:v1.18.6-k3s1   "/bin/k3s agent"         22 hours ago        Up 22 hours                                                   k3d-nemesis-cluster-agent-2
4f2bc8370100        rancher/k3s:v1.18.6-k3s1   "/bin/k3s agent"         22 hours ago        Up 22 hours                                                   k3d-nemesis-cluster-agent-1
a45c1a926e30        rancher/k3s:v1.18.6-k3s1   "/bin/k3s agent"         22 hours ago        Up 22 hours                                                   k3d-nemesis-cluster-agent-0
124ade58aac9        rancher/k3s:v1.18.6-k3s1   "/bin/k3s server --t…"   22 hours ago        Exited (255) 17 hours ago                                     k3d-nemesis-cluster-server-2
0a899a45d37e        rancher/k3s:v1.18.6-k3s1   "/bin/k3s server --t…"   22 hours ago        Exited (139) 17 hours ago                                     k3d-nemesis-cluster-server-1
f31ead93be87        rancher/k3s:v1.18.6-k3s1   "/bin/k3s server --c…"   22 hours ago        Exited (139) 20 hours ago                                     k3d-nemesis-cluster-server-0
```

Any help would be greatly appreciated.

**Comment by iwilltry42** [comment]
Hi @sjbeskur , looks like all your server nodes crashed. If you can checkout the logs of them (`docker logs`), you'll probably notice some lines talking about leader election failing, etc. This is a k3s-internal issue caused by dqlite, which always requires a quota of servers. So if there's an error in 1 out of 3 nodes, dqlite will fail leader election, making all the server nodes crash.
