### ISSUE TITLE
`make prep` destructive action without double confirm

### ISSUE THREAD

**Issue by southwolf** [iwilltry42/k3d-demo#11]
The `make prep` command will delete containers / images / volumes, such destructive command should require user READ instructions and DOUBLE even TRIPLE confirm.

**Comment by iwilltry42** [comment]
Hi @southwolf , you're right there!
I created this repo for my own demoing purposes back then and so I didn't think of additional safety measures.
Fixed it in 48a6d18  now, hoping that two levels of confirmation are enough :+1:
