### ISSUE TITLE
load balancer does not seem to work on centos7

### ISSUE THREAD

**Issue by oscar6echo** [iwilltry42/k3d-demo#12]
@iwilltry42 this repo is a very useful k3d demo, with many tips packed.  
Thanks for sharing it !

It works flawlessly on my ubuntu 20.04 machine.  
However I noticed that on a Centos7 VM the load balancer does not work.

+ If you run `make demo` and stop after the first stage (cluster creation) on Ubuntu I get:
```bash
> curl localhost:8080
404 page not found
```

+ On a Centos7 machine:
```bash
> curl localhost:8080
Empty reply from server
```

The following steps do not change this output.

Inspecting container `k3d-demo-serverlb` logs and processes I could not pinpoint the problem.  
At least pinging from one container to another using theirs name works:
```bash
#### inside k3d-demo-server-0
/ # ping k3d-demo-agent-0
PING k3d-demo-agent-0 (172.19.0.4): 56 data bytes
64 bytes from 172.19.0.4: seq=0 ttl=64 time=0.077 ms
64 bytes from 172.19.0.4: seq=1 ttl=64 time=0.080 ms
```

I wonder if this is a tiny config glitch, or some serious low level limitation...

What do you think ?

**Comment by oscar6echo** [comment]
Well, well, I found the cause for the issue.  
It is **completely independent** of k3d and embarrassingly basic.. 

The Centos7 VM is behind a corporate firewall.  
The pods in name space `kube-system` could not load their images.  
That became clear doing:
```bash
kubectl get -A
```
Closing.

**Comment by iwilltry42** [comment]
@oscar6echo , thanks for the feedback! :)
Glad you could solve your issue :+1:
