### ISSUE TITLE
bug: the number of servers on reflected

### ISSUE THREAD

**Issue by mavogel** [iwilltry42/k3d-demo#6]
Quick reminder from the great demo: 

## Expected behavior

3 servers spin up

## Current behavior
The number of servers is not reflected: https://github.com/iwilltry42/k3d-demo/blob/main/assets/k3d-config.yaml#L4
Only 1 server spins up

**Comment by iwilltry42** [comment]
:joy: Thanks a lot!
Thanks for joining and for the feedback :)
We'll follow up over here: https://github.com/rancher/k3d/issues/458
