### ISSUE TITLE
Deploy the sample app with helm step fails with "unable to build kubernetes objects" error on Mac

### ISSUE THREAD

**Issue by murindwaz** [iwilltry42/k3d-demo#7]
On a Macbook pro-2019 (Intel i9), while following steps in the demo, the Helm deployment step fails with the following error:

```shell
# Step: Deploy the sample app with helm
# Command: helm upgrade --install sample-app sample/conf/charts/sample-app --namespace demo --set app.image=sample-app:local [Enter]
$ helm upgrade --install sample-app sample/conf/charts/sample-app --namespace demo --set app.image=sample-app:local
Release "sample-app" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1"
```

**Note:**

- I have k8s installed from source for other learning experiences
- I have k3s installed by default from k3d (v4.3.0) 
- Docker and Kubernetes are always up to date

**Comment by JasonGhent** [comment]
```
--- a/sample/conf/charts/sample-app/templates/web.yaml
+++ b/sample/conf/charts/sample-app/templates/web.yaml
@@ -3,7 +3,7 @@
 {{- $name := printf "%s-%s" $app $component -}}

 {{- if .Values.app.domain }}
-apiVersion: networking.k8s.io/v1
+apiVersion: networking.k8s.io/v1beta1
 kind: Ingress
 metadata:
   name: "{{ $name }}"
@@ -19,10 +19,8 @@ spec:
           - path: /
             pathType: ImplementationSpecific
             backend:
-              service:
-                name: {{ $name }}
-                port:
-                  number: {{ .Values.app.port }}
+              serviceName: {{ $name }}
+              servicePort: {{ .Values.app.port }}
```

Same issue on m1 mba. This fixed it for me. Seems to have [changed in a commit last month](https://github.com/iwilltry42/k3d-demo/commit/83eab014444e6c604d760607d66863750cba76ee).

**Comment by iwilltry42** [comment]
Hi @murindwaz, thanks for opening this issue!
And thanks @JasonGhent for the provided patch :+1: 
This change was introduced to make the demo ready for k3s/k8s v1.20.x to use the stable API for Ingress.
Not sure, if it's worth putting a `Capabilities` switch in the chart to automatically switch between the API-Versions.. wdyt?

**Comment by murindwaz** [comment]
Thanks, @iwilltry42 for this awesome tool.
For this question **_"Capabilities switch in the chart to automatically switch between the API-Versions"_** ~ I think It makes sense. If I understand well that would prevent changing the chart version every time there is a new one. 

Also thanks @JasonGhent for a quick fix.
